server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjpa
    password: springjpa
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  


## 공용 DB 
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@220.85.6.86:50256:xe
#    username: jd
#    password: jd
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#
#  jpa:
#   generate-ddl: true
##    hibernate:
##      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#      
##logging.level:
##  org.hibernate.SQL: debug
##  org.hibernate.type: trace
  